#!/usr/bin/env bash

protocol="newt"
cargo build --release --bin ${protocol}
cargo build --release --bin client

for id in 1 2 3; do
    proc ${protocol} ${id} >.log_process_${id} 2>&1 &
done
sleep 1

for id in 1 2 3; do
    started=""

    while [[ ${started} != "1" ]]; do
        started=$(grep -c "process ${id} started" .log_process_${id} | xargs)
    done
done
echo "> processes started"

for id in 1 2 3; do
    client ${id} >.log_client_${id} 2>&1 &
done
sleep 1
echo "> clients started"

for id in 1 2 3; do
    ended=""

    while [[ ${ended} != "1" ]]; do
        started=$(grep -c "client ${id} started" .log_client_${id} | xargs)
        sleep 1
    done
done
echo "> clients ended"

bench_stop
