#!/usr/bin/env bash

release="--release"
release=""

case $1 in
1) 
  cargo run ${release} --bin client -- --id 1 --address localhost:4001 --commands_per_client 10000 --interval 1
  ;;
2)
  cargo run ${release} --bin client -- --id 2 --address localhost:4002 --commands_per_client 10000 --interval 1
  ;;
3)
  cargo run ${release} --bin client -- --id 3 --address localhost:4003 --commands_per_client 10000 --interval 1
  ;;
*)
  echo "client id $0 invalid"
  ;;
esac
