#!/usr/bin/env bash

case $1 in
1) 
  cargo run --bin process -- --id 1 --port 3001 --addresses localhost:3002,localhost:3003 --client_port 4001
  ;;
2)
  cargo run --bin process -- --id 2 --port 3002 --addresses localhost:3001,localhost:3003 --client_port 4002
  ;;
3)
  cargo run --bin process -- --id 3 --port 3003 --addresses localhost:3001,localhost:3002 --client_port 4003
  ;;
*)
  echo "process id $0 invalid"
  ;;
esac
