#!/usr/bin/env bash

protocol=$1
release="--release"

case $2 in
1) 
  cargo run ${release} --bin ${protocol} -- --id 1 --sorted 1,2,3 --port 3001 --addresses localhost:3002,localhost:3003 --client_port 4001 --processes 3 --faults 1
  ;;
2)
  cargo run ${release} --bin ${protocol} -- --id 2 --sorted 2,3,1 --port 3002 --addresses localhost:3001,localhost:3003 --client_port 4002 --processes 3 --faults 1
  ;;
3)
  cargo run ${release} --bin ${protocol} -- --id 3 --sorted 3,1,2 --port 3003 --addresses localhost:3001,localhost:3002 --client_port 4003 --processes 3 --faults 1
  ;; 
*)
  echo "process id $0 invalid"
  ;;
esac
